export const oneLiners = {
  "Dirty Nice": "Basically The Strokes ",
  "Brown Horse": "UK americana - Corduroy couch",
  "Callinsick": "Sam Fender vibes",
  "Classic Trucks": "alt country / indie guy",
  "DBA!": "Liverpool alternative / catchy ",
  "DUG": "Irish/Americana steel guitar - Jubilee",
  "Humane The Moon": "Catchy indie tunes",
  "Mên An Tol": "Clean indie anthems - NW1",
  "YAANG": "Indie alt-rave sweaty",
  "Tina Sandwich": "Scottish indie pop (celtic)",
  "The Sick Man of Europe": "New order style",
  "The New Cut": "A bit like Yard Act",
  "The Roebucks": "Harmonies galore",
  "Public Circuit": "NY synth pop",
  "Neon Lies": "Synth pop",
  "naya mö": "Indie bangers",
  "Baby Smith": "Catchy soft indie pop",
  "Delivery Service": "Female indie irish",
  "Honk": "Let the dog see the rabbit",
  "Laundromat Chicks": "Jangly pop tunes",
  "Madra Salach": "Irish folk - Wallopers light",
  "Mumble Tide": "Gentle indie female vocal",
  "Big Long Sun": "Catchy soft indie",
  "I Dreamed I Dream": "Irish shoe-gaze. Smoking fags",
  "Infinity Knives & Brian Ennals": "Rappers angry with israel",
  "Kean Kavanagh": "Irish dark cowboy reverb",
  "Molly Payton": "Sharon von Etten vibes",
  "ZONBI": "Carribean jazz punk",
  "Zac Lawrence": "UK singer songwriter",
  "Zach Thompson": "Dylan rip off",
  "Vieira and The Silvers": "bluesy garage psych with a twang",
  "Pollyfromthedirt": "lo-fi indie",
  "Theatre": "Irish shoe-gaze",
  "Star City": "Synth rock",
  "She's in parties": "Dream pop",
  "Silver Gore": "indie pop",
  "Sean Trelford": "Bedroom rock",
  "Elwell": "Cribs-ish",
  "Honey I'm Home": "Dutch shoegaze",
  // "Jo from School": "youngster, indie pop",
  // "Lino Camilo": "Could be odd but interesting",
  "Little Grandad": "London americana indie mix",
  "Wolfschmidt": "Swedish nugaze indie - too heavy",
};

// Not needed
export const timetable = [
  { "day": "Thu", "stage": "ANNABEL DOWN", "artist": "Silver Gore", "start": "19:00", "end": "19:40" },
  { "day": "Thu", "stage": "ANNABEL DOWN", "artist": "Tina Sandwich", "start": "20:30", "end": "21:10" },
  { "day": "Thu", "stage": "ARMINIUS", "artist": "Mên An Tol", "start": "19:00", "end": "19:40" },
  { "day": "Thu", "stage": "ARMINIUS", "artist": "Big Long Sun", "start": "22:00", "end": "22:40" },
  { "day": "Thu", "stage": "CLUB CENTRAAL", "artist": "YAANG", "start": "22:00", "end": "22:40" },
  { "day": "Thu", "stage": "ROTOWN", "artist": "Brown Horse", "start": "19:20", "end": "20:00" },
  { "day": "Thu", "stage": "SALSABILITY", "artist": "Baby Smith", "start": "20:00", "end": "20:40" },
  { "day": "Thu", "stage": "SALSABILITY", "artist": "Infinity Knives & Brian Ennals", "start": "23:00", "end": "23:40" },
  { "day": "Thu", "stage": "THE CUBE (PLAN C)", "artist": "The New Cut", "start": "19:30", "end": "20:10" },
  { "day": "Thu", "stage": "THE CUBE (PLAN C)", "artist": "Pollyfromthedirt", "start": "20:50", "end": "21:30" },
  { "day": "Thu", "stage": "THE CUBE (PLAN C)", "artist": "Public Circuit", "start": "23:30", "end": "00:10" },
  { "day": "Thu", "stage": "THEATER ROTTERDAM", "artist": "Star City", "start": "19:50", "end": "20:30" },
  { "day": "Thu", "stage": "THEATER ROTTERDAM", "artist": "Zac Lawrence", "start": "21:20", "end": "22:00" },
  { "day": "Thu", "stage": "THEATER ROTTERDAM", "artist": "DBA!", "start": "22:50", "end": "23:30" },
  { "day": "Thu", "stage": "V11", "artist": "The Sick Man of Europe", "start": "20:40", "end": "21:20" },
  { "day": "Thu", "stage": "V11", "artist": "Vieira and The Silvers", "start": "22:00", "end": "22:40" },
  { "day": "Thu", "stage": "WATERFRONT", "artist": "Honk", "start": "19:00", "end": "19:40" },
  { "day": "Thu", "stage": "WATERFRONT", "artist": "Theatre", "start": "22:00", "end": "22:40" },
  { "day": "Thu", "stage": "WORM 2", "artist": "Neon Lies", "start": "21:40", "end": "22:20" },
  { "day": "Fri", "stage": "ANNABEL DOWN", "artist": "The New Cut", "start": "18:10", "end": "18:50" },
  { "day": "Fri", "stage": "ARMINIUS", "artist": "Kean Kavanagh", "start": "16:00", "end": "16:40" },
  { "day": "Fri", "stage": "ARMINIUS", "artist": "Pollyfromthedirt", "start": "17:30", "end": "18:10" },
  { "day": "Fri", "stage": "ARMINIUS", "artist": "Brown Horse", "start": "20:30", "end": "21:10" },
  { "day": "Fri", "stage": "BIBLIOTHEEK - CAFÉ", "artist": "Zach Thompson", "start": "20:50", "end": "21:30" },
  { "day": "Fri", "stage": "BIBLIOTHEEK - THEATER", "artist": "Molly Payton", "start": "18:20", "end": "19:00" },
  { "day": "Fri", "stage": "DE DOELEN STUDIO 1", "artist": "Sean Trelford", "start": "20:00", "end": "20:40" },
  { "day": "Fri", "stage": "DE DOELEN UP", "artist": "Laundromat Chicks", "start": "17:50", "end": "18:30" },
  { "day": "Fri", "stage": "PARADIJSKERK", "artist": "Zac Lawrence", "start": "16:50", "end": "17:30" },
  { "day": "Fri", "stage": "PARADIJSKERK", "artist": "DUG", "start": "19:50", "end": "20:30" },
  { "day": "Fri", "stage": "PERRON BIG", "artist": "YAANG", "start": "17:00", "end": "17:40" },
  { "day": "Fri", "stage": "PERRON BIG", "artist": "Silver Gore", "start": "22:00", "end": "22:40" },
  { "day": "Fri", "stage": "PERRON SMALL", "artist": "Big Long Sun", "start": "16:10", "end": "16:50" },
  { "day": "Fri", "stage": "PERRON SMALL", "artist": "Junk Drawer", "start": "19:30", "end": "20:10" },
  { "day": "Fri", "stage": "ROODKAPJE EXPO", "artist": "Classic Trucks", "start": "22:30", "end": "23:10" },
  { "day": "Fri", "stage": "ROODKAPJE FRONT", "artist": "Mumble Tide", "start": "18:20", "end": "19:00" },
  { "day": "Fri", "stage": "ROODKAPJE FRONT", "artist": "I Dreamed I Dream", "start": "20:00", "end": "20:40" },
  { "day": "Fri", "stage": "ROODKAPJE FRONT", "artist": "She's In Parties", "start": "23:20", "end": "00:00" },
  { "day": "Fri", "stage": "ROTOWN", "artist": "Theatre", "start": "19:00", "end": "19:40" },
  { "day": "Fri", "stage": "ROTOWN", "artist": "DBA!", "start": "22:00", "end": "22:40" },
  { "day": "Fri", "stage": "SALSABILITY", "artist": "Vieira and The Silvers", "start": "17:50", "end": "18:30" },
  { "day": "Fri", "stage": "THE CUBE (PLAN C)", "artist": "Humane the Moon", "start": "22:00", "end": "22:40" },
  { "day": "Fri", "stage": "THE CUBE (PLAN C)", "artist": "Dirty Nice", "start": "23:30", "end": "00:10" },
  { "day": "Fri", "stage": "THEATER ROTTERDAM", "artist": "Baby Smith", "start": "16:40", "end": "17:20" },
  { "day": "Fri", "stage": "THEATER ROTTERDAM", "artist": "Madra Salach", "start": "20:00", "end": "20:40" },
  { "day": "Fri", "stage": "THEATER ROTTERDAM", "artist": "Callinsick", "start": "21:40", "end": "22:20" },
  { "day": "Fri", "stage": "THEATER ROTTERDAM", "artist": "Wolfschmidt", "start": "23:20", "end": "00:00" },
  { "day": "Fri", "stage": "V11", "artist": "Honk", "start": "16:40", "end": "17:20" },
  { "day": "Fri", "stage": "V11", "artist": "Tina Sandwich", "start": "19:40", "end": "20:20" },
  { "day": "Fri", "stage": "V2_", "artist": "Neon Lies", "start": "16:40", "end": "17:20" },
  { "day": "Fri", "stage": "V2_", "artist": "Delivery Service", "start": "22:40", "end": "23:20" },
  { "day": "Fri", "stage": "WATERFRONT", "artist": "Mên An Tol", "start": "19:50", "end": "20:30" },
  { "day": "Fri", "stage": "WORM 1", "artist": "Public Circuit", "start": "21:10", "end": "21:50" },
  { "day": "Fri", "stage": "WORM 2", "artist": "The Sick Man of Europe", "start": "23:40", "end": "00:20" },
  { "day": "Fri", "stage": "160K - ARCADE", "artist": "Infinity Knives & Brian Ennals", "start": "18:40", "end": "19:20" },
  { "day": "Fri", "stage": "160K - DANCE HALL", "artist": "elwell", "start": "17:50", "end": "18:30" },
  { "day": "Fri", "stage": "160K - DANCE HALL", "artist": "Star City", "start": "21:10", "end": "21:50" },
  { "day": "Fri", "stage": "160K - DANCE HALL", "artist": "naya mö", "start": "22:50", "end": "23:30" },
  { "day": "Sat", "stage": "ANNABEL DOWN", "artist": "Dirty Nice", "start": "16:40", "end": "17:20" },
  { "day": "Sat", "stage": "ANNABEL DOWN", "artist": "Humane the Moon", "start": "18:10", "end": "18:50" },
  { "day": "Sat", "stage": "ANNABEL UP", "artist": "Lino Camilo", "start": "17:20", "end": "18:00" },
  { "day": "Sat", "stage": "ANNABEL UP", "artist": "Honey I'm Home", "start": "18:50", "end": "19:30" },
  { "day": "Sat", "stage": "ANNABEL UP", "artist": "The Roebucks", "start": "23:20", "end": "00:00" },
  { "day": "Sat", "stage": "ARMINIUS", "artist": "Molly Payton", "start": "17:30", "end": "18:10" },
  { "day": "Sat", "stage": "BIBLIOTHEEK - THEATER", "artist": "DUG", "start": "16:40", "end": "17:20" },
  { "day": "Sat", "stage": "BIBLIOTHEEK - THEATER", "artist": "Mumble Tide", "start": "20:00", "end": "20:40" },
  { "day": "Sat", "stage": "CLUB CENTRAAL", "artist": "Sean Trelford", "start": "18:50", "end": "19:30" },
  { "day": "Sat", "stage": "CLUB CENTRAAL", "artist": "Lino Camilo", "start": "23:20", "end": "00:00" },
  { "day": "Sat", "stage": "DE DOELEN STUDIO 1", "artist": "Junk Drawer", "start": "23:00", "end": "23:40" },
  { "day": "Sat", "stage": "DE DOELEN UP", "artist": "I Dreamed I Dream", "start": "20:50", "end": "21:30" },
  { "day": "Sat", "stage": "DE DOELEN UP", "artist": "Molly Payton", "start": "22:20", "end": "23:00" },
  { "day": "Sat", "stage": "PARADIJSKERK", "artist": "Callinsick", "start": "16:50", "end": "17:30" },
  { "day": "Sat", "stage": "PARADIJSKERK", "artist": "Zach Thompson", "start": "19:50", "end": "20:30" },
  { "day": "Sat", "stage": "PARADIJSKERK", "artist": "Madra Salach", "start": "21:20", "end": "22:00" },
  { "day": "Sat", "stage": "PARADIJSKERK", "artist": "Classic Trucks", "start": "22:50", "end": "23:30" },
  { "day": "Sat", "stage": "PERRON SMALL", "artist": "Honey I'm Home", "start": "22:50", "end": "23:30" },
  { "day": "Sat", "stage": "ROODKAPJE EXPO", "artist": "The Roebucks", "start": "19:10", "end": "19:50" },
  { "day": "Sat", "stage": "ROODKAPJE EXPO", "artist": "Big Long Sun", "start": "20:50", "end": "21:30" },
  { "day": "Sat", "stage": "ROODKAPJE FRONT", "artist": "Wolfschmidt", "start": "20:00", "end": "20:40" },
  { "day": "Sat", "stage": "ROODKAPJE FRONT", "artist": "little grandad", "start": "23:20", "end": "00:00" },
  { "day": "Sat", "stage": "ROTOWN", "artist": "Kean Kavanagh", "start": "22:00", "end": "22:40" },
  { "day": "Sat", "stage": "SALSABILITY", "artist": "Tina Sandwich", "start": "16:20", "end": "17:00" },
  { "day": "Sat", "stage": "THE CUBE (PLAN C)", "artist": "She's In Parties", "start": "20:30", "end": "21:10" },
  { "day": "Sat", "stage": "THEATER ROTTERDAM", "artist": "naya mö", "start": "18:20", "end": "19:00" },
  { "day": "Sat", "stage": "THEATER ROTTERDAM", "artist": "Laundromat Chicks", "start": "20:00", "end": "20:40" },
  { "day": "Sat", "stage": "UNIEK", "artist": "Delivery Service", "start": "16:50", "end": "17:30" },
  { "day": "Sat", "stage": "V2_", "artist": "little grandad", "start": "16:40", "end": "17:20" },
  { "day": "Sat", "stage": "V2_", "artist": "Callinsick", "start": "21:10", "end": "21:50" },
  { "day": "Sat", "stage": "WORM 2", "artist": "elwell", "start": "18:40", "end": "19:20" }
]

export const priorities = {
  'Dirty Nice': 7,
  'Callinsick': 7,
  'Brown Horse': 6,
  'Classic Trucks': 6,
  'DBA!': 6,
  'DUG': 6,
  'Humane the Moon': 6,
  'Mên An Tol': 6,
  'naya mö': 6,
  'YAANG': 5,
  'The Sick Man of Europe': 5,
  'The New Cut': 5,
  'Public Circuit': 5,
  'Neon Lies': 5,
  'Baby Smith': 5,
  'Delivery Service': 5,
  'Honk': 5,
  'Laundromat Chicks': 5,
  'Madra Salach': 5,
  'Tina Sandwich': 4,
  'The Roebucks': 4,
  'Mumble Tide': 4,
  'Big Long Sun': 4,
  'I Dreamed I Dream': 4,
  'Kean Kavanagh': 4,
  'Molly Payton': 4,
  'Infinity Knives & Brian Ennals': 3,
  'Zac Lawrence': 3,
  'Zach Thompson': 3,
  'Pollyfromthedirt': 3,
  'Theatre': 3,
  'Star City': 3,
  "She's In Parties": 3,
  'Silver Gore': 3,
  'Elwell': 3,
  "Honey I'm Home": 3,
  'Junk Drawer': 3,
  'Lino Camilo': 3,
  'Little Grandad': 3,
  'Sean Trelford': 2,
  'Wolfschmidt': 2,
  'Vieira and The Silvers': 2,
};
